### PR TITLE
Unsupported instruction trap handler test

### PR DESCRIPTION
**Pull request by samuelgruetter**
Here's a test case which tries to run an interrupt handler in case the M extension is not available.

The test fails, and I don't fully understand why. 

Observerd behavior: If the `mul` instruction is not available, its destination register is overwritten with 0, and no trap handler is run.

Expected behavior: If the `mul` instruction is not available, the destination register is left unmodified, and the trap handler is run.

### CODE REVIEW

**Comment by threonorm** [comment]
Thanks, very interesting. I believe it is a bug introduced by the new decoder. My opinion is that we should decode a mul as an invalid instruction (that was the intention back then). But now we are sharing the decoder with every implementation so we are decoding as a Mul instead of a Invalid, and then boom.

Maybe we should just pass the output of the decoder in a filter that would make sure that it is not overdecoding. Or to write a more parametrized decoder (ultimately we want a dynamically parametrized decoder)

**Comment by benjaminselfridge** [comment]
@threonorm Can i ask why you feel it needs to be dealt with on the decoding side rather than semantics? I'm also looking at the code for the semantics and wondering what the issue is. If we encounter an unimplemented instruction like Mul in a context where we don't have the M extension, won't it just be mzero in that case? Why can't we just throw an error when we detect that situation?

**Comment by threonorm** [comment]
That's correct, that was sort of the intention with the previous fall through case (that I did not think through properly and then triggered the bug of overwriting exceptions (PR #15 ), because mzero end up having two semantics: mzero coming from an exception raised by an early execute function in the list, and mzero coming from an unsupported instruction, that we want to catch.).

 I agree that it would be possible to do that technique of filtering in execute properly (and avoid triggering the other bug when doing so), but semantically after thinking about it I am not a huge fan of InvalidInstruction being triggered in two different context (when an instruction is improperly decoded, and also in exec when we realize it's not supported).

I find it a bit convoluted and mostly a "nice way to achieve that in this haskell spec",  instead of the way I would think about it when writing some hardware, in which I would know at decode time that the instruction is not supported.

Though in the case where the extensions dynamically change,  maybe I would do that later in exec.
So I am not entirely set.
I think we should discuss that in today's conf call in  -40seconds. 

Any opinion?

**Comment by benjaminselfridge** [comment]
I hear your concerns, especially the aversion to doing it because it's a "nice way" to do it rather than the RIGHT way.

My question to you (and perhaps others) is -- does the manual say anywhere what is supposed to happen if the ? Would it signal an illegal instruction? If that is the case, then it seems clear to me that mzero *should* be made to also throw an illegal instruction, along with actually illegal instructions. As far as RV32I is concerned, mul *is* illegal. That's how I think of it, anyway. But it's probably important to get some official word on what is supposed to happen.

**Comment by samuelgruetter** [comment]
I just pushed a fix which filters out unsupported instructions at the end of the `decode` function, and also gets rid of `MonadPlus`, what do you think of it?

**Comment by threonorm** [comment]
@samuelgruetter  I am reviewing it (I had bad experience with higher order functions and memory usage in Clahs before), it looks good (the decoder a tiny bit verbose).

@benjaminselfridge: 

> - does the manual say anywhere what is supposed to happen if the processor encounters a non-implemented, rather than strictly illegal, instruction? Would it signal an illegal instruction?

Not that I know of. Also I know of implementations that are RV32I but do support mul (but not div). It seems reasonable for the spec to not prevent those implementations to exist, or to claim that they are rv32i (even though there are a bit more).

> As far as RV32I is concerned, mul is illegal.

As a first approximation I agree, that's why I suggest we just decode it as an InvalidInstruction for now, and say that those problems will be entirely pushed in the decoder (it will be for the decoder to decide what is invalid and what is not).

To come back to mzero, I think we don't want mzero to have any RISCV semantical meaning. We just thought of MonadPlus as an easy way to merge execute functions partially defined from n files having the invariant:
every case is defined exactly once (in exactly one of those files).

**Comment by rsnikhil** [comment]
>    does the manual say anywhere what is supposed to happen if the
>    processor encounters a non-implemented, rather than strictly
>    illegal, instruction? Would it signal an illegal instruction?

I believe there is no difference between 'unimplemented' and
'illegal'.  So, if the implem does not support 'M', both MUL and DIV
would be illegal.

If an implem claims to support 'M', it can choose to implement one or
both in HW or SW.  If in SW, it would start with an illegal instr
trap; the trap handler would recognize an attempt at MUL/DIV, emulate
it, produce the result, and return.

>    As a first approximation I agree, that's why I suggest we just
>    decode it as an InvalidInstruction for now, and say that those
>    problems will be entirely pushed in the decoder (it will be for
>    the decoder to decide what is invalid and what is not).

Yes. As we discussed in today's con-call, especially for a Spec, I
think it's cleaner to catch illegal instrs in the Decoder.

When I first wrote the decoder, I had postponed the task of passing in
MISA as an arg to the decoder, which would govern what it it treated
as legal/illegal.  The initial quick-and-dirty solution was to pass
xlen, and only treat RV64-only instructions as illegal if xlen=32.

>     To come back to mzero, I think we don't want mzero to have any
>    RISCV semantical meaning. We just thought of MonadPlus as an easy
>    way to merge execute functions partially defined from n files
>    having the invariant: every case is defined exactly once (in
>    exactly one of those files).

I agree. We shouldn't mix 'mzero' to mean both "not relevant for the
executes I deal with" and also "illegal instruction".

Nikhil

**Comment by samuelgruetter** [comment]
Just pushed an update: By introducing separate types for instructions of different extensions, I addressed both concerns of @threonorm: 
*    The verbose part of the decoder, `applyByExtInstructionMapper`, is not needed any more
*    No new higher order functions introduced

**Pull request merged**
